# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaacioly
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-auth
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-auth

stages:
  default:
    params:
      tableName: "users"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: index.handler
    environment:
      USERS_TABLE: ${param:tableName}
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
