# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaacioly
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-auth
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-auth

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
